name: 'http-api-client'
concurrency: 'build'

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set git config
        run: |
           git config user.name github-actions
           git config user.email github-actions@github.com

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: :http-api-client:jvmTest :http-api-client:iosX64Test

      - name: Update docs
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./gradlew dokkaHtml
          git add http-api-client/docs/
          git commit -m 'Updated docs' || echo "No changes to docs"
          git push

      - name: Publish to Sonatype
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/publish.sh http-api-client
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}

      - name: Push changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git push
          git push --tags
